# Generated by Django 2.2.4 on 2020-06-11 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('create_time', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('people', models.IntegerField()),
                ('isCheck', models.BooleanField(default=False)),
            ],
        ),
    ]
